use std::{env, fs, path::PathBuf, process::Command};

fn main() {
    install_git_hooks_path();

    let mut src_path = PathBuf::from("src");
    src_path.push("lib");
    src_path.push("protos");
    src_path.push("RadarMessage.proto");

    let out_dir = env::var_os("OUT_DIR").unwrap();
    let mut dest_path = PathBuf::from(&out_dir);
    dest_path.push("lib");
    dest_path.push("protos");
    fs::create_dir_all(&dest_path).unwrap();

    protobuf_codegen::Codegen::new()
        .pure()
        // All inputs and imports from the inputs must reside in `includes` directories.
        .includes(["src/lib/protos"])
        // Inputs must reside in some of include paths.
        .input("src/lib/protos/RadarMessage.proto")
        // Specify output directory relative to Cargo output directory.
        .cargo_out_dir("lib/protos")
        .run_from_script();

    let mut v3_api = PathBuf::from("web");
    v3_api.push("api");
    fs::create_dir_all(&v3_api).unwrap();
    v3_api.push("RadarMessage.proto");
    fs::copy(&src_path, &v3_api).unwrap();

    // The GUI lives in web/gui/ in this repository and is embedded at compile
    // time by rust-embed.
    let gui_dir = PathBuf::from("web").join("gui");

    println!("cargo:rustc-env=MAYARA_GUI_DIR={}", gui_dir.display());

    // Read api-version from [package.metadata] in Cargo.toml
    let api_version = env::var("CARGO_PKG_METADATA_API_VERSION").unwrap_or_else(|_| {
        // Fallback: parse Cargo.toml directly
        let toml = fs::read_to_string("Cargo.toml").expect("Cannot read Cargo.toml");
        for line in toml.lines() {
            if let Some(v) = line.strip_prefix("api-version") {
                let v = v.trim().trim_start_matches('=').trim().trim_matches('"');
                return v.to_string();
            }
        }
        panic!("api-version not found in [package.metadata]");
    });
    println!("cargo:rustc-env=SIGNALK_RADAR_API_VERSION={}", api_version);

    // Permeate the Radar API version into the embedded GUI so it can enforce
    // ^major.minor compatibility against whatever server it talks to (accept an
    // equal-or-newer minor, refuse an older API or a new major). Generated from
    // the single api-version source; not tracked in git.
    fs::create_dir_all(&gui_dir).unwrap();
    fs::write(
        gui_dir.join("api-version.js"),
        format!(
            "// Generated by build.rs from Cargo.toml [package.metadata] api-version.\n\
             // Do not edit; not tracked in git.\n\
             export const RADAR_API_VERSION = \"{}\";\n",
            api_version
        ),
    )
    .unwrap();

    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=Cargo.toml");
    println!("cargo::rerun-if-changed=src/protos/RadarMessage.proto");
}

/// Point this clone's `core.hooksPath` at `.githooks/` on first `cargo build`,
/// so contributors get the pre-commit `cargo fmt` check without having to
/// run `git config` themselves. Cheap and idempotent:
///
/// - Skips when we're not in a git working tree (e.g. crates.io packaged
///   builds or `cargo vendor` output).
/// - Skips when `.githooks/pre-commit` is missing.
/// - Skips when `core.hooksPath` is already set to anything other than
///   `.githooks` — contributors who configured their own hooks path are
///   left alone (a one-line `cargo:warning=` tells them what they're
///   missing).
fn install_git_hooks_path() {
    println!("cargo:rerun-if-changed=.githooks/pre-commit");

    if !PathBuf::from(".git").is_dir() {
        return;
    }
    if !PathBuf::from(".githooks/pre-commit").is_file() {
        return;
    }

    let current = Command::new("git")
        .args(["config", "--local", "--get", "core.hooksPath"])
        .output();
    let current = match current {
        Ok(out) => String::from_utf8_lossy(&out.stdout).trim().to_string(),
        Err(_) => return, // git not on PATH — nothing useful we can do.
    };

    if current == ".githooks" {
        return; // Already wired up.
    }
    if !current.is_empty() {
        println!(
            "cargo:warning=core.hooksPath is set to '{}'; leaving it alone. \
             Set it to '.githooks' to enable the repo's pre-commit cargo fmt check.",
            current
        );
        return;
    }

    let _ = Command::new("git")
        .args(["config", "--local", "core.hooksPath", ".githooks"])
        .status();
}
