#!/usr/bin/env python3
"""Summarize samply profile.json.gz files into a comparison table.

Reads one or more profile files generated by `tests/perf/run.sh`. For each,
filters tokio-worker stacks into running vs. parked (so the macOS samply
default of sampling sleeping threads doesn't dilute the headline numbers),
then prints:

  - a markdown comparison table across all profiles
  - per-profile top-N self-time functions

Usage:
    python3 analyze.py PROFILE.json.gz [PROFILE.json.gz ...]
"""

import gzip
import json
import sys
from bisect import bisect_right
from collections import Counter
from pathlib import Path

PARK_HINTS = (
    "_pthread_cond_wait",
    "__psynch_cvwait",
    "park_internal",
    "park_remote",
    "park_thread",
    "mach_msg2_trap",
    "park_caller",
    "Driver::park",
    "park_timeout",
)


def build_resolver(module):
    sym_table = module["symbol_table"]
    starts = [e["rva"] for e in sym_table]
    order = sorted(range(len(starts)), key=lambda i: starts[i])
    sorted_rvas = [starts[i] for i in order]
    sorted_entries = [sym_table[i] for i in order]
    known = {a: idx for a, idx in module.get("known_addresses", [])}

    def resolve(rva):
        if rva in known:
            return sorted_entries[known[rva]]
        i = bisect_right(sorted_rvas, rva) - 1
        if i < 0:
            return None
        e = sorted_entries[i]
        if e["rva"] <= rva < e["rva"] + e["size"]:
            return e
        return None

    return resolve


def symbolicate(name, resolvers, strtab):
    if not name.startswith("0x"):
        return name
    rva = int(name, 16)
    for r in resolvers:
        e = r(rva)
        if e is None:
            continue
        sym_idx = e.get("symbol")
        if sym_idx is None and e.get("frames"):
            sym_idx = e["frames"][-1].get("function")
        if sym_idx is not None:
            return strtab[sym_idx]
    return name


def is_parked(stack):
    return any(any(h in sym for h in PARK_HINTS) for sym in stack)


def find_syms_for(profile_path: Path) -> Path | None:
    candidates = [
        Path(str(profile_path).removesuffix(".gz") + ".syms.json"),
        Path(str(profile_path).replace(".json.gz", ".json.syms.json")),
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


def analyze_profile(path: Path):
    sym_path = find_syms_for(path)
    if sym_path is None:
        raise SystemExit(f"No .syms.json sidecar found for {path}")

    with gzip.open(path, "rb") as f:
        profile = json.load(f)
    with open(sym_path) as f:
        syms = json.load(f)

    strtab = syms["string_table"]
    resolvers = [build_resolver(m) for m in syms["data"]]

    parked = 0
    running = 0
    self_count: Counter = Counter()

    for t in profile["threads"]:
        if not t["name"].startswith("tokio-rt"):
            continue
        if len(t["samples"]["stack"]) < 50:
            continue
        strings = t["stringArray"]
        funcs = t["funcTable"]
        frames = t["frameTable"]
        stack_tbl = t["stackTable"]
        for stack_idx in t["samples"]["stack"]:
            if stack_idx is None:
                continue
            cur = stack_idx
            stack_syms = []
            while cur is not None:
                frame_idx = stack_tbl["frame"][cur]
                func_idx = frames["func"][frame_idx]
                name = strings[funcs["name"][func_idx]]
                stack_syms.append(symbolicate(name, resolvers, strtab))
                cur = stack_tbl["prefix"][cur]
            if is_parked(stack_syms):
                parked += 1
            else:
                running += 1
                if stack_syms:
                    self_count[stack_syms[0]] += 1

    return {
        "name": path.name.replace(".json.gz", ""),
        "total": parked + running,
        "parked": parked,
        "running": running,
        "top": self_count.most_common(15),
    }


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} PROFILE.json.gz [...]", file=sys.stderr)
        sys.exit(2)

    results = []
    for p in sys.argv[1:]:
        path = Path(p)
        if not path.exists():
            print(f"Skip missing: {p}", file=sys.stderr)
            continue
        results.append(analyze_profile(path))

    print("# Profile summary")
    print()
    print("Tokio worker stacks, split between parked (idle, in `_pthread_cond_wait`")
    print("or `park_internal`) and running. Top self-time is computed over running")
    print("samples only.")
    print()
    print("| Profile | Tokio samples | Parked | Running | Top self-time fn (%) |")
    print("| --- | ---: | ---: | ---: | --- |")
    for r in results:
        if r["total"] == 0:
            print(f"| {r['name']} | 0 | — | — | (no samples) |")
            continue
        parked_pct = r["parked"] * 100 / r["total"]
        running_pct = r["running"] * 100 / r["total"]
        if r["top"] and r["running"]:
            top_name, top_count = r["top"][0]
            top_pct = top_count * 100 / r["running"]
            top_str = f"{top_name[:80]} ({top_pct:.1f}%)"
        else:
            top_str = "—"
        print(
            f"| {r['name']} | {r['total']} | {parked_pct:.0f}% "
            f"| {running_pct:.0f}% | {top_str} |"
        )

    for r in results:
        print()
        print(f"## {r['name']}")
        if r["running"] == 0:
            print("(no running samples)")
            continue
        print(
            f"Tokio samples: {r['total']} "
            f"(parked {r['parked']}, running {r['running']})"
        )
        print()
        print("| % | Count | Function |")
        print("| ---: | ---: | --- |")
        for name, c in r["top"]:
            print(f"| {c * 100 / r['running']:.1f}% | {c} | {name[:140]} |")


if __name__ == "__main__":
    main()
