name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: cargo fmt --check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v7
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: swatinem/rust-cache@v2
      with:
        key: clippy
    - name: cargo clippy (default features)
      run: cargo clippy --no-deps --all-targets -- -D warnings
    - name: cargo clippy (--features pcap-replay)
      run: cargo clippy --no-deps --all-targets --features pcap-replay -- -D warnings

  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl, x86_64-pc-windows-gnu]

    steps:

    - name: Checkout
      uses: actions/checkout@v7
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - uses: swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}

    - name: Install Cross
      run: cargo install cross

    - name: Build
      run: cross build --release --target ${{ matrix.target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: mayara-server for ${{ matrix.target }}
        path: target/${{ matrix.target }}/release/mayara-server*

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - uses: swatinem/rust-cache@v2
    - name: Run tests
      run: cargo test --features pcap-replay --release
    - name: Build
      run: cargo build --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: Mayara Windows x86_64
        path: target/release/mayara-server.exe

  macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7
    - uses: swatinem/rust-cache@v2
    - uses: taiki-e/install-action@v2.85.12
      with:
        tool: nextest
    - name: Run tests
      run: cargo nextest run --features pcap-replay
    - name: Build
      run: cargo build --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: Mayara macOS
        path: target/release/mayara-server
